# Site settings
author: "Ryan Amaral"
title: "Ryan Amaral ∙ Android Engineer"
title_header: "ryanamaral.com"
description: "Android Engineer Portfolio"
analytics: UA-61486844-1
base_url: ""
url: "https://ryanamaral.com"

webrick: # development server used to preview the site locally
  headers:
    Access-Control-Allow-Origin: "*" # allow http://localhost

markdown: kramdown
permalink: /:categories/:title

colors:  #in hex code if not noted else
  primary: "#7db8c9"
  primary_rgb: "125,185,201" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#2b3642"
  yellow: "#BB7722"
  blue: "#1B5299"
  white: "#FFFFFF"
  link: "#428bca"
  link_hover: "#BB7722"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

social:
  - title: linkedin
    url: https://www.linkedin.com/in/ryanamaral
  - title: github
    url: https://github.com/ryanamaral
  - title: stack-overflow
    url: https://stackoverflow.com/users/904907/ryan-amaral

company_list:
  - name: "LeYa"
    img: leya.png
  - name: Bubble
    img: bubble.png
  - name: "BOLD Internacional"
    img: bold-internacional.png
  - name: "Público"
    img: publico.png
  - name: M2mobi
    img: m2mobi.png
  - name: iClio
    img: iclio.png

about_title: "Hi there 👋"
about: "I'm Ryan Amaral. I am an enthusiastic Android developer currently working as a contractor. I took my Bachelor of Engineering in Computer Science degree in Coimbra, Portugal. In 2012 I published a personal Android app that reached the mark of 10 million downloads! Working on new ideas is my greatest passion! While crafting applications I apply the most up-to-date practices of Android development that I learn every year at Droidcon's around Europe."

recommendation:
    message: "\"Ryan, great friend and college classmate, is a very disciplined, responsible and with excellent leadership skills and team spirit person, having the ability to work efficiently under stressful conditions and tight deadlines. A professional with excellent high technical knowledge, always available to provide solutions to any challenge. Software development is his world, complete with Scrum techniques allied with IntelliJ IDEA and intensive use of Git. Java is his language of choice complemented with the use of JSON, XML, RESTful WebServices and SQLite. In mobile development raves about Android, which has shown great success due to their commitment and professionalism.\""
    author: Sérgio Duarte Fernandes
    position: Core and Access Network at Portugal Telecom

people:
  - message: "\"I've had the privilege to be working with Ryan in mobile development related projects for more than a year. During this period Ryan has demonstrated an exemplar commitment, giving an exceptional technical contribute in the Android development area. He has faced and overcome enormous challenges on legacy code management and refactoring and has brought an essential technical input for the project success. Ryan has also shown to have excellent team skills, as an easy-going, constructive and caring person, even at the most stressful times.\""
    author: João Fernandes
    position: Head of Technology at Grupo Leya
  - message: "\"Ryan, great friend and college classmate, is a very disciplined, responsible and with excellent leadership skills and team spirit person, having the ability to work efficiently under stressful conditions and tight deadlines. A professional with excellent high technical knowledge, always available to provide solutions to any challenge. Software development is his world, complete with Scrum techniques allied with IntelliJ IDEA and intensive use of Git. Java is his language of choice complemented with the use of JSON, XML, RESTful WebServices and SQLite. In mobile development raves about Android, which has shown great success due to their commitment and professionalism.\""
    author: Sérgio Duarte Fernandes
    position: Core and Access Network at Portugal Telecom
